# Generated by Django 2.0.5 on 2018-05-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='album_artist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='composer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
